/**
 * Inline target-project fixtures. The IMPLEMENTATION_PLAN §B suggests
 * vendoring real public projects for full Stage 2 integration, but Stage 1
 * only needs the Phase 1 scan to handle a tiny but realistic shape.
 *
 * These helpers stand up a fully-formed npm project (package.json +
 * package-lock.json) in a scratch directory.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

export interface SmallProjectOptions {
  name?: string;
  includeVolta?: boolean;
  workspaces?: boolean;
  packageManager?: 'npm' | 'yarn-classic' | 'yarn-berry';
}

export async function createSmallNpmProject(dir: string, opts: SmallProjectOptions = {}): Promise<string> {
  const name = opts.name ?? 'small-modern';
  const pkg: Record<string, unknown> = {
    name,
    version: '1.0.0',
    private: true,
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1'
    },
    devDependencies: {
      typescript: '^5.5.3'
    }
  };
  if (opts.includeVolta) {
    pkg.volta = { node: '18.19.0', npm: '10.2.3' };
  }
  if (opts.workspaces) {
    pkg.workspaces = ['packages/*'];
  }
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, 'package.json'), JSON.stringify(pkg, null, 2));

  if (opts.packageManager === 'yarn-classic') {
    await fs.writeFile(
      path.join(dir, 'yarn.lock'),
      `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\nreact@^18.3.1:\n  version "18.3.1"\n  resolved "https://registry.yarnpkg.com/react/-/react-18.3.1.tgz"\n  integrity sha512-aaaaaa\n  dependencies:\n    loose-envify "^1.1.0"\n\nreact-dom@^18.3.1:\n  version "18.3.1"\n  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-18.3.1.tgz"\n  integrity sha512-bbbbbb\n  dependencies:\n    scheduler "^0.23.2"\n\ntypescript@^5.5.3:\n  version "5.5.3"\n  resolved "https://registry.yarnpkg.com/typescript/-/typescript-5.5.3.tgz"\n  integrity sha512-cccccc\n`
    );
  } else if (opts.packageManager === 'yarn-berry') {
    await fs.writeFile(
      path.join(dir, 'yarn.lock'),
      `# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: 6\n  cacheKey: 8\n\n"react@npm:^18.3.1":\n  version: 18.3.1\n  resolution: "react@npm:18.3.1"\n  checksum: deadbeef\n\n"react-dom@npm:^18.3.1":\n  version: 18.3.1\n  resolution: "react-dom@npm:18.3.1"\n  checksum: cafef00d\n\n"typescript@npm:^5.5.3":\n  version: 5.5.3\n  resolution: "typescript@npm:5.5.3"\n  checksum: feedface\n`
    );
  } else {
    // npm lockfile v3 minimal shape
    const lock = {
      name,
      version: '1.0.0',
      lockfileVersion: 3,
      requires: true,
      packages: {
        '': {
          name,
          version: '1.0.0',
          dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
          devDependencies: { typescript: '^5.5.3' }
        },
        'node_modules/react': { version: '18.3.1', name: 'react' },
        'node_modules/react-dom': { version: '18.3.1', name: 'react-dom' },
        'node_modules/scheduler': { version: '0.23.2', name: 'scheduler' },
        'node_modules/typescript': { version: '5.5.3', name: 'typescript' }
      }
    };
    await fs.writeFile(path.join(dir, 'package-lock.json'), JSON.stringify(lock, null, 2));
  }
  return dir;
}

export interface LegacyProjectOptions {
  depCount?: number;
}

export async function createLegacyNpmProject(dir: string, opts: LegacyProjectOptions = {}): Promise<string> {
  const count = opts.depCount ?? 150;
  const dependencies: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};
  const packages: Record<string, { version: string; name: string }> = {};
  for (let i = 0; i < count; i += 1) {
    const name = `legacy-pkg-${i.toString().padStart(3, '0')}`;
    const version = `1.${i % 5}.${i % 10}`;
    if (i % 5 === 0) devDependencies[name] = `^${version}`;
    else dependencies[name] = `^${version}`;
    packages[`node_modules/${name}`] = { version, name };
  }
  const pkg = {
    name: 'large-legacy',
    version: '0.5.0',
    private: true,
    dependencies,
    devDependencies
  };
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, 'package.json'), JSON.stringify(pkg, null, 2));
  const lock = {
    name: 'large-legacy',
    version: '0.5.0',
    lockfileVersion: 3,
    requires: true,
    packages: {
      '': { name: 'large-legacy', version: '0.5.0', dependencies, devDependencies },
      ...packages
    }
  };
  await fs.writeFile(path.join(dir, 'package-lock.json'), JSON.stringify(lock, null, 2));
  return dir;
}

/**
 * Snapshot every file under a directory into a map of relative-path → sha256.
 * Used by the target-read-only invariant test (§16.3).
 */
export async function snapshotDirectory(root: string): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  await walk(root, root, out);
  return out;
}

async function walk(base: string, current: string, out: Record<string, string>): Promise<void> {
  const crypto = await import('node:crypto');
  const entries = await fs.readdir(current, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(current, entry.name);
    const rel = path.relative(base, full).split(path.sep).join('/');
    if (entry.isDirectory()) {
      await walk(base, full, out);
      continue;
    }
    if (entry.isFile()) {
      const buf = await fs.readFile(full);
      const hash = crypto.createHash('sha256').update(buf).digest('hex');
      out[rel] = `${hash}:${buf.length}`;
    }
  }
}
