/**
 * Lockfile detection + parsing (spec §6.2 / §10.3 / §10.1 Phase 1).
 *
 * Detects npm | yarn-classic | yarn-berry, parses each, and computes:
 *   - lockfileHash: sha256 of raw bytes
 *   - lockfileStateHash: sha256 over sorted `name@version` pairs of the
 *     resolved package set (so reformatting doesn't bust caches — §8.2).
 *
 * Resolution preference: npm wins when both present (per §6.2).
 */
import { promises as fs } from 'fs';
import path from 'path';
import crypto from 'crypto';

export type PackageManager = 'npm' | 'yarn-classic' | 'yarn-berry';

export interface ResolvedPackage {
  name: string;
  version: string;
}

export interface ResolvedPackageWithDepth extends ResolvedPackage {
  /**
   * Depth of the install path in node_modules nesting. 1 = root install
   * (`node_modules/<name>`), 2 = first-level nested
   * (`node_modules/a/node_modules/<name>`), and so on. Phase-1 uses this to
   * pick the *root* version when multiple installs of the same package exist
   * (the direct-dep lookup must reflect the package the project actually
   * imports, not a transitive deduped under a sibling).
   */
  depth: number;
}

export interface LockfileSummary {
  packageManager: PackageManager;
  lockfilePath: string;
  lockfileHash: string;
  lockfileStateHash: string;
  /** Map from `name` → installed version for direct top-level lookups. */
  installedVersions: Record<string, string>;
  /** Full resolved set (sorted by name@version). */
  resolvedPackages: ResolvedPackage[];
}

export interface DetectedLockfile {
  packageManager: PackageManager;
  lockfilePath: string;
}

/**
 * Returns null when no supported lockfile exists.
 * npm wins when both package-lock.json and yarn.lock are present.
 */
export async function detectLockfile(projectDir: string): Promise<DetectedLockfile | null> {
  const npmLock = path.join(projectDir, 'package-lock.json');
  const yarnLock = path.join(projectDir, 'yarn.lock');

  if (await fileExists(npmLock)) {
    return { packageManager: 'npm', lockfilePath: npmLock };
  }
  if (await fileExists(yarnLock)) {
    const header = await readFirstBytes(yarnLock, 512);
    const flavour = detectYarnFlavour(header);
    return { packageManager: flavour, lockfilePath: yarnLock };
  }
  return null;
}

/**
 * Yarn classic vs berry detection by file header. Berry lockfiles begin with
 * a YAML doc with `__metadata:` block and `version: 6` (or similar). Classic
 * lockfiles begin with a comment `# THIS IS AN AUTOGENERATED FILE…` and have
 * no YAML mapping at top.
 */
export function detectYarnFlavour(header: string): 'yarn-classic' | 'yarn-berry' {
  if (header.includes('__metadata:') || /^\s*__metadata\b/m.test(header)) {
    return 'yarn-berry';
  }
  return 'yarn-classic';
}

async function fileExists(p: string): Promise<boolean> {
  try {
    const stat = await fs.stat(p);
    return stat.isFile();
  } catch {
    return false;
  }
}

async function readFirstBytes(filePath: string, n: number): Promise<string> {
  const fh = await fs.open(filePath, 'r');
  try {
    const buf = Buffer.alloc(n);
    const { bytesRead } = await fh.read(buf, 0, n, 0);
    return buf.subarray(0, bytesRead).toString('utf8');
  } finally {
    await fh.close();
  }
}

function sha256(buf: Buffer | string): string {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

function stateHashFromResolved(resolved: ResolvedPackage[]): string {
  const sorted = [...resolved]
    .map((p) => `${p.name}@${p.version}`)
    .sort();
  return sha256(sorted.join('\n'));
}

export async function parseLockfile(detected: DetectedLockfile): Promise<LockfileSummary> {
  const raw = await fs.readFile(detected.lockfilePath);
  const lockfileHash = sha256(raw);

  let resolved: ResolvedPackageWithDepth[];
  if (detected.packageManager === 'npm') {
    resolved = parseNpmLock(JSON.parse(raw.toString('utf8')) as NpmLock);
  } else if (detected.packageManager === 'yarn-classic') {
    resolved = await parseYarnClassic(raw.toString('utf8'));
  } else {
    resolved = await parseYarnBerry(raw.toString('utf8'));
  }

  // Sort by (name, depth, version). Stable shallowest-first ordering ensures
  // installedVersions[name] reflects the *root-level* install when multiple
  // entries for the same package exist (e.g. `node_modules/foo` and
  // `node_modules/bar/node_modules/foo` with different versions — the project
  // imports the root one).
  const sorted = [...resolved].sort((a, b) => {
    if (a.name !== b.name) return a.name.localeCompare(b.name);
    if (a.depth !== b.depth) return a.depth - b.depth;
    return a.version.localeCompare(b.version);
  });

  const installed: Record<string, string> = {};
  for (const { name, version } of sorted) {
    if (installed[name] === undefined) installed[name] = version;
  }

  // Strip the internal depth field from the public resolvedPackages list.
  const publicResolved: ResolvedPackage[] = sorted.map(({ name, version }) => ({ name, version }));

  return {
    packageManager: detected.packageManager,
    lockfilePath: detected.lockfilePath,
    lockfileHash,
    lockfileStateHash: stateHashFromResolved(publicResolved),
    installedVersions: installed,
    resolvedPackages: publicResolved
  };
}

interface NpmLock {
  lockfileVersion?: number;
  packages?: Record<string, { version?: string; name?: string }>;
  dependencies?: Record<string, { version?: string; dependencies?: Record<string, unknown> }>;
}

function parseNpmLock(json: NpmLock): ResolvedPackageWithDepth[] {
  const out: ResolvedPackageWithDepth[] = [];
  // Lockfile v2/v3: `packages` keyed by node_modules path.
  if (json.packages !== undefined) {
    for (const [pkgPath, meta] of Object.entries(json.packages)) {
      if (pkgPath === '') continue; // root project entry
      const name = meta.name ?? extractNameFromNodeModulesPath(pkgPath);
      if (name === null) continue;
      if (meta.version === undefined) continue;
      out.push({ name, version: meta.version, depth: nodeModulesDepth(pkgPath) });
    }
    return out;
  }
  // Lockfile v1: nested `dependencies` — depth is the recursion level.
  if (json.dependencies !== undefined) {
    walkV1(json.dependencies, out, 1);
    return out;
  }
  return out;
}

/**
 * Count how many `node_modules/` segments appear in the path. A root install
 * (`node_modules/foo`) is depth 1; a transitive nested under a sibling
 * (`node_modules/bar/node_modules/foo`) is depth 2; and so on.
 */
function nodeModulesDepth(pkgPath: string): number {
  let depth = 0;
  for (const segment of pkgPath.split('/')) {
    if (segment === 'node_modules') depth += 1;
  }
  return depth === 0 ? 1 : depth;
}

function walkV1(
  deps: Record<string, { version?: string; dependencies?: Record<string, unknown> }>,
  out: ResolvedPackageWithDepth[],
  depth: number
): void {
  for (const [name, meta] of Object.entries(deps)) {
    if (typeof meta.version === 'string') {
      out.push({ name, version: meta.version, depth });
    }
    if (meta.dependencies !== undefined && typeof meta.dependencies === 'object') {
      walkV1(
        meta.dependencies as Record<string, { version?: string; dependencies?: Record<string, unknown> }>,
        out,
        depth + 1
      );
    }
  }
}

function extractNameFromNodeModulesPath(p: string): string | null {
  // "node_modules/foo" or "node_modules/@scope/pkg" or nested
  const segments = p.split('/');
  const lastNm = segments.lastIndexOf('node_modules');
  if (lastNm === -1) return null;
  const after = segments.slice(lastNm + 1);
  if (after.length === 0) return null;
  if (after[0]!.startsWith('@')) {
    if (after.length < 2) return null;
    return `${after[0]}/${after[1]}`;
  }
  return after[0]!;
}

async function parseYarnClassic(content: string): Promise<ResolvedPackageWithDepth[]> {
  // Dynamic import keeps the static dependency graph lean and lets tests run
  // without @yarnpkg/lockfile when only npm fixtures are exercised.
  const lockfileMod = await import('@yarnpkg/lockfile');
  // Handle both ESM and CJS interop shapes (parse may live on default).
  const parse = (lockfileMod as { parse?: typeof lockfileMod.parse; default?: { parse?: typeof lockfileMod.parse } }).parse
    ?? (lockfileMod as { default?: { parse?: typeof lockfileMod.parse } }).default?.parse;
  if (parse === undefined) {
    throw new Error('@yarnpkg/lockfile.parse not available');
  }
  const parsed = parse(content);
  const out: ResolvedPackageWithDepth[] = [];
  for (const [key, meta] of Object.entries(parsed.object)) {
    // key e.g. "react@^18.2.0" or "@types/react@^18.0.0, @types/react@^18.0.1"
    const firstKey = key.split(',')[0]!.trim();
    const lastAt = firstKey.lastIndexOf('@');
    if (lastAt <= 0) continue;
    const name = firstKey.slice(0, lastAt);
    // Yarn classic uses a flat dedupe-everything model — every entry is
    // effectively a root-equivalent install for the purposes of this lookup.
    out.push({ name, version: meta.version, depth: 1 });
  }
  return out;
}

async function parseYarnBerry(content: string): Promise<ResolvedPackageWithDepth[]> {
  const parsersMod = (await import('@yarnpkg/parsers')) as unknown as {
    parseSyml?: (s: string) => Record<string, unknown>;
    default?: { parseSyml: (s: string) => Record<string, unknown> };
  };
  const parseSyml = parsersMod.parseSyml ?? parsersMod.default?.parseSyml;
  if (parseSyml === undefined) {
    throw new Error('@yarnpkg/parsers.parseSyml not available');
  }
  const parsed = parseSyml(content);
  const out: ResolvedPackageWithDepth[] = [];
  for (const [key, value] of Object.entries(parsed)) {
    if (key === '__metadata') continue;
    if (typeof value !== 'object' || value === null) continue;
    const meta = value as { version?: string };
    if (typeof meta.version !== 'string') continue;
    const firstKey = key.split(',')[0]!.trim();
    const lastAt = firstKey.lastIndexOf('@');
    if (lastAt <= 0) continue;
    const name = firstKey.slice(0, lastAt);
    // Yarn berry is similarly flat (PnP / single-version-per-name resolver).
    out.push({ name, version: meta.version, depth: 1 });
  }
  return out;
}
