import { describe, it, expect, afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { createSandbox, disposeAllSandboxes, type Sandbox } from './helpers/sandbox';
import { createSmallNpmProject } from './helpers/fixtures';
import { detectLockfile, detectYarnFlavour, parseLockfile } from '@/lib/scanners/lockfile';

let sandbox: Sandbox | undefined;

afterEach(async () => {
  if (sandbox !== undefined) await sandbox.dispose();
  await disposeAllSandboxes();
});

describe('lockfile detection', () => {
  it('detects npm when only package-lock.json present', async () => {
    sandbox = await createSandbox('lf-npm');
    const dir = await sandbox.scratch('proj');
    await createSmallNpmProject(dir);
    const det = await detectLockfile(dir);
    expect(det?.packageManager).toBe('npm');
  });

  it('npm wins when both package-lock.json and yarn.lock are present', async () => {
    sandbox = await createSandbox('lf-both');
    const dir = await sandbox.scratch('proj');
    await createSmallNpmProject(dir);
    await fs.writeFile(path.join(dir, 'yarn.lock'), '# yarn classic header\n');
    const det = await detectLockfile(dir);
    expect(det?.packageManager).toBe('npm');
  });

  it('detects yarn-classic by header when only yarn.lock present', async () => {
    sandbox = await createSandbox('lf-yarn-classic');
    const dir = await sandbox.scratch('proj');
    await createSmallNpmProject(dir, { packageManager: 'yarn-classic' });
    // remove package-lock.json so yarn.lock wins
    await fs.rm(path.join(dir, 'package-lock.json'), { force: true });
    const det = await detectLockfile(dir);
    expect(det?.packageManager).toBe('yarn-classic');
  });

  it('detects yarn-berry by __metadata header', async () => {
    sandbox = await createSandbox('lf-yarn-berry');
    const dir = await sandbox.scratch('proj');
    await createSmallNpmProject(dir, { packageManager: 'yarn-berry' });
    await fs.rm(path.join(dir, 'package-lock.json'), { force: true });
    const det = await detectLockfile(dir);
    expect(det?.packageManager).toBe('yarn-berry');
  });

  it('returns null when no lockfile present', async () => {
    sandbox = await createSandbox('lf-none');
    const dir = await sandbox.scratch('proj');
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, 'package.json'), '{"name":"x"}');
    const det = await detectLockfile(dir);
    expect(det).toBeNull();
  });
});

describe('yarn flavour detection by header', () => {
  it('classifies classic when no __metadata block', () => {
    const header = '# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n\n';
    expect(detectYarnFlavour(header)).toBe('yarn-classic');
  });
  it('classifies berry when __metadata block present', () => {
    const header = '# This file is generated...\n\n__metadata:\n  version: 6\n';
    expect(detectYarnFlavour(header)).toBe('yarn-berry');
  });
});

describe('lockfile parsing', () => {
  it('extracts resolved packages from npm lockfile v3', async () => {
    sandbox = await createSandbox('lf-parse-npm');
    const dir = await sandbox.scratch('proj');
    await createSmallNpmProject(dir);
    const det = await detectLockfile(dir);
    if (det === null) throw new Error('detect failed');
    const lf = await parseLockfile(det);
    expect(lf.installedVersions.react).toBe('18.3.1');
    expect(lf.installedVersions.typescript).toBe('5.5.3');
    expect(lf.lockfileHash).toMatch(/^[0-9a-f]{64}$/);
    expect(lf.lockfileStateHash).toMatch(/^[0-9a-f]{64}$/);
  });

  it('prefers root install over nested transitive when both versions exist', async () => {
    // Regression for M7: a project with `foo` at the project root and a
    // transitive `foo` nested under `bar` (different version) must report the
    // *root* version as installedVersions[foo], because that is the version
    // the project actually imports. Without depth-aware sorting, the smaller
    // version (lexicographic) wins, which silently mis-reports outdatedness.
    sandbox = await createSandbox('lf-root-vs-nested');
    const dir = await sandbox.scratch('proj');
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ name: 'root-vs-nested', version: '1.0.0', dependencies: { foo: '^18.0.0' } })
    );
    const lock = {
      name: 'root-vs-nested',
      version: '1.0.0',
      lockfileVersion: 3,
      requires: true,
      packages: {
        '': { name: 'root-vs-nested', version: '1.0.0', dependencies: { foo: '^18.0.0' } },
        'node_modules/foo': { version: '18.3.1' },
        'node_modules/bar': { version: '2.0.0' },
        'node_modules/bar/node_modules/foo': { version: '17.0.2' }
      }
    };
    await fs.writeFile(path.join(dir, 'package-lock.json'), JSON.stringify(lock, null, 2));
    const det = await detectLockfile(dir);
    if (det === null) throw new Error('detect failed');
    const lf = await parseLockfile(det);
    expect(lf.installedVersions.foo).toBe('18.3.1');
    // Sanity: both entries are in the resolved set.
    const fooEntries = lf.resolvedPackages.filter((p) => p.name === 'foo').map((p) => p.version);
    expect(fooEntries.sort()).toEqual(['17.0.2', '18.3.1']);
  });

  it('lockfileStateHash is stable across reformatting', async () => {
    sandbox = await createSandbox('lf-state-hash');
    const dirA = await sandbox.scratch('a');
    const dirB = await sandbox.scratch('b');
    await createSmallNpmProject(dirA);
    await createSmallNpmProject(dirB);
    const fpA = path.join(dirA, 'package-lock.json');
    const fpB = path.join(dirB, 'package-lock.json');
    // Reformat B with different whitespace
    const raw = await fs.readFile(fpA, 'utf8');
    const parsed = JSON.parse(raw);
    await fs.writeFile(fpB, JSON.stringify(parsed)); // no indent
    const detA = await detectLockfile(dirA);
    const detB = await detectLockfile(dirB);
    if (detA === null || detB === null) throw new Error('detect failed');
    const lfA = await parseLockfile(detA);
    const lfB = await parseLockfile(detB);
    expect(lfA.lockfileHash).not.toBe(lfB.lockfileHash); // raw bytes differ
    expect(lfA.lockfileStateHash).toBe(lfB.lockfileStateHash); // resolved set is identical
  });
});
